version: '2'
services:
  zookeeper:
    container_name: karafka_20_zookeeper
    image: wurstmeister/zookeeper
    restart: on-failure
    ports:
      - '2181:2181'

  kafka:
    container_name: karafka_20_kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS:
        "benchmarks_00_01:1:1,\
         benchmarks_00_05:5:1,\
         benchmarks_01_05:5:1,\
         benchmarks_00_10:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
