# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '6.1.7.3'
gem 'activesupport', '6.1.7.3'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'railties', '6.1.7.3'
