# frozen_string_literal: true

source 'https://rubygems.org'

if RUBY_VERSION >= '3.4'
  gem 'bigdecimal'
  gem 'drb'
  gem 'mutex_m'
end

gem 'activerecord', '6.1.7.6'
gem 'activesupport', '6.1.7.6'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'railties', '6.1.7.6'
gem 'rspec-rails'
