# frozen_string_literal: true

# This code is part of Karafka Pro, a commercial component not licensed under LGPL.
# See LICENSE for details.

source 'https://rubygems.org'

gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'rails', '8.0.1', require: true
