# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '8.1.0'
gem 'activesupport', '8.1.0'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'railties', '8.1.0'
gem 'rspec-rails'
