# frozen_string_literal: true

source 'https://rubygems.org'

gem 'benchmark'
gem 'bigdecimal'
gem 'concurrent-ruby', '1.3.4'
gem 'drb'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'logger'
gem 'mutex_m'
gem 'rails', '7.0.8.7'
