# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activemodel', '7.2.2.2'
gem 'activesupport', '7.2.2.2'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'karafka-web', '>= 0.10.1'
gem 'railties', '7.2.2.2'
