# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '7.1.3'
gem 'activemodel', '7.1.3'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'karafka-web', '>= 0.8.0'
gem 'railties', '7.1.3'
