# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '8.0.2'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'karafka-web', '0.9.0'
gem 'railties', '8.0.2'
