# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'puma', '6.0.0', require: true
gem 'sinatra', '3.0.2', require: true
