# frozen_string_literal: true

source 'https://rubygems.org'

if RUBY_VERSION >= '3.4'
  gem 'bigdecimal'
  gem 'drb'
  gem 'mutex_m'
end

gem 'activerecord', '7.0.8'
gem 'activesupport', '7.0.8'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'logger'
gem 'railties', '7.0.8'
gem 'rspec-rails'
