# frozen_string_literal: true

source 'https://rubygems.org'

if RUBY_VERSION >= '3.4'
  gem 'bigdecimal'
  gem 'drb'
  gem 'mutex_m'
end

gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'rails', '7.1.5.1'
