# frozen_string_literal: true

source "https://rubygems.org"

gem "karafka", path: ENV.fetch("KARAFKA_GEM_DIR"), require: true
gem "puma", "7.1.0", require: true
gem "rackup", require: true
gem "sinatra", "4.2.1", require: true
