# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '7.1.5.1'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'karafka-web', '0.7.10'
gem 'railties', '7.1.5.1'
