# frozen_string_literal: true

# This code is part of Karafka Pro, a commercial component not licensed under LGPL.
# See LICENSE for details.

source 'https://rubygems.org'

if RUBY_VERSION >= '3.4'
  gem 'bigdecimal'
  gem 'drb'
  gem 'mutex_m'
end

gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'rails', '7.0.8.7', require: true
