# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '7.1.3'
gem 'activesupport', '7.1.3'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'railties', '7.1.3'
