# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '7.0.4.2'
gem 'activesupport', '7.0.4.2'
gem 'karafka', path: ENV.fetch('KARAFKA_GEM_DIR'), require: true
gem 'railties', '7.0.4.2'
gem 'rspec-rails'
