name: Push Gem

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  push:
    if: github.repository_owner == 'karafka'
    runs-on: ubuntu-latest
    environment: deployment

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          bundler-cache: false

      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3

      - uses: rubygems/release-gem@052cc82692552de3ef2b81fd670e41d13cba8092 # v1.4.0
