name: Push Gem

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  push:
    if: github.repository_owner == 'karafka'
    runs-on: ubuntu-latest
    environment: deployment

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          bundler-cache: false

      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3

      - uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7 # v1.2.0
