name: Push Gem

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  push:
    if: github.repository_owner == 'karafka'
    runs-on: ubuntu-latest
    environment: deployment

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          bundler-cache: false

      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3

      - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1
